### PR TITLE
add instructions for building from source

### PR DESCRIPTION
**Pull request by eharrow**
I wanted to build from source myself and so documented the simple steps.

### CODE REVIEW

**Comment by astlouys** [comment]
Hi Ewan,

Thank you for contributing to the Pico-Green-Clock !  It's a good idea to add this procedure for those who want to work on the code and are not familiar.

Thanks again, and do not hesitate to join us in the discussion group.

André

**Comment by UltrashRicco** [comment]
Hello, not sure why but these instructions do not work for me.

Instead of `export PICO_SDK_PATH=../../pico-sdk` I have to pass the path to the SDK to cmake directly from the command line: `cmake .. -DPICO_SDK_PATH=../../pico-sdk/` otherwise I get an error.

Only needed the first time running 'cmake ..' afterwards it is OK.

**Comment by eharrow** [comment]
> Hello, not sure why but these instructions do not work for me.
> 
> Instead of `export PICO_SDK_PATH=../../pico-sdk` I have to pass the path to the SDK to cmake directly from the command line: `cmake .. -DPICO_SDK_PATH=../../pico-sdk/` otherwise I get an error.
> 
> Only needed the first time running `cmake ..` afterwards it is OK.

Windows, Linux or Mac?

**Comment by eharrow** [comment]
> Linux... I had the same issue both on a Raspberry Pi 4 running Raspbian OS and on a x64 PC running Ubuntu.

Thats interesting as the export ought to do the job and that is what is stated in the toolchain setup in the referenced pdf specifically for developing on a raspberry pi.

Presumably `PICO_SDK_PATH=../../pico-sdk cmake …   ` would work as well.

**Comment by astlouys** [comment]
Hi Eric,

This is strange... Could you make some checks:

Open a terminal box on your system...

1) If you try:    ls  -l  ~/pico
   Do you see the   pico-sdk   directory in the list that is displayed (there must be a "d" in the leftmost column to indicate that it is a directory).

2) Referring to the same list that you displayed in 1) above, do you see the directory of your project (for example:  Pico-Clock-Green)   ?

3) If you display your project directory  (for example:   ls  -l   ~/pico/Pico-Clock-Green
   Do you see the    build     directory ?

4) If you try:   export
   Do you see an entry indicating:     declare PICO_SDK_PATH="../../pico-sdk"     ?

5) In your project directory (for example:  Pico-Clock-Green), do you see the file:    pico_sdk_import.cmake     ?
   Is it the file itself that you see or a symbolic link ?  (Working with a symbolic link allows you to work with the most recent SDK libraries, assuming that you update your SDK when a new version becomes available)..

**Comment by UltrashRicco** [comment]
Hi guys, thanks for the help, as mentionned I managed to have it work with `cmake .. -DPICO_SDK_PATH=../../pico-sdk/`

    1. yes
Capture d’écran du 2022-12-10 22-10-50

    2. yes!

    3. yes, I created the build directory myself with `sudo mkdir build`
image

    4. No, the pico-sdk path is not declared in there. I guess this is the source of my initial issue. I installed the toolchain by running the script available in the Raspberry Pi Pico documentation. It supposedly installs everything that is needed.

    5. Yes, I had to copy this file from another project or example directory, I do not believe I am using a symlink.

Thanks for the help! I must have missed a step somewhere during the toolchain installation, or the automated installation script lack this specific configuration. This seems likely, as I installed it on both devices the very same way.

**Comment by astlouys** [comment]
Eric,

I'm surprised to see that most of your files have user:group  "root:root" (but it is not related to your problem.

I think this should solve your problem:

1) Make a backup of your current    .bashrc     file (it is small, but there is a "dot" as the first character.
cd ~
pwd      (make sure you are in   /home/pi    directory
cp  .bashrc    .bashrc-BACKUP-10-DEC-2022

2) Then, use your preferred text editor and add the following line at the end of your   .bashrc    file

export  PICO_SDK_PATH=/home/pi/pico/pico-sdk
export  PICO_EXAMPLES_PATH=/home/pi/pico/pico-examples
export  PICO_EXTRAS_PATH=/home/pi/pico/pico-extras
export  PICO_PLAYGROUND_PATH=/home/pi/pico/pico-playground

3) As far as I remember, you need to close and re-open another terminal screen before typing   export   and see the result.
If it does not work, you may reboot the system (not sure if it is required).  This should solve your problem with the SDK path (and the other paths indicated as well).

**Comment by UltrashRicco** [comment]
Hi André, thank you, I tried your commands to no avail. This is the error I am getting:

image

Eharrow's suggestion  does not work for me either: `sudo PICO_SDK_PATH=../../pico-sdk cmake`
image

The only way I can get cmake to work is by passing the sdk path as an argument with `sudo cmake -DPICO_SDK_PATH=../../pico-sdk ..`

I use root (through sudo) quite often to circumvent priviledge issues. Pretty sure I ran the pico toolchain installation script as root too, otherwise I would get errors with the execution of the script. Consequently, the whole /home/pi/pico directory seems to be owned by root.

I am quite fine with using sudo, I do not need to be able to compile pico binaries as a simple user, as I do not use such tools on a daily basis at all.

I do appreciate the effort, guys, but I do not feel like this is an issue that needs solving, since I am able to compile just fine, and it definitely is not related to this project!

I just thought I would explain (in my first message) how I managed to sort it out when `export PICO_SDK_PATH=../../pico-sdk` won't work (just pass the sdk path to cmake in the command line).

Sorry for wasting your time, thanks again!

**Comment by astlouys** [comment]
Hi Eric,

OK then. At least you can go through the build process...

I can't point to the exact source of the problem from the screens you sent, but I suspect that installing the toolchain as root may give that kind of side effects...

**Pull request merged**
