### PR TITLE
Correct the hour comparison for the alarm, hour chime and night light…

### PR DESCRIPTION
**Pull request by cmcornish**
… features.

The CurrentHour takes values of between 1-12 when running in 12Hr mode. The alarm, hour chime and night light hours are stored in FlashConfig in 24 hr mode with values of 0-23. Use the 24hr values in CurrentHourSetting for the comparisons. This corrects the failures of afternoon alarmsand double triggering when running in 12Hr mode.

### CODE REVIEW

**Comment by cmcornish** [comment]
Hello Andre,

I have bought a couple of these based on your good work and extensions for the Waveshare design. Thank you for your work on this.
I found an issue with alarms being set for afternoons when running in 12Hr mode. The alarms are in 24hr hour values. I've tweaked the code to address this.
Please accept this correction (after proper review).

Thanks,
Chris.

**Comment by astlouys** [comment]
P. S. Changes don't seem to be added to the code... I must repeat that I didn't take the time to learn all the benefits that I can get from GitHub (I should !). Would you be kind enough to let me know what are the commands to integrate your code (obviously, the commands that I followed were wrong)...

**Comment by cmcornish** [comment]
Hi André,

 

I’m not a great GIT user myself – just starting out as I’ve been using SVN. I‘ve not yet had to merge in a request onto any of my projects. I tried this a long while ago and the person I was feeding code to sent me a terse e-mail in the commants that I didn’t understand. 

 

There is something on GitHub’s documentation – I thought it should be managed by the account web interface. Is this the method you used?
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request

 

I think it should be painless as there shouldn’t be any conflicts. At least I hope so.

 

I have another change that allows disabling the ringing alarm beeps using any of the buttons – this was more an experiment on how to use GitHub than any valid change. I can send that too if you want another merge request to play with (after this one has completed).

I’ve also added a hostname to the design to identify the clock in a DHCP table and I’m in the process of adding a web control interface. This is taking a bit longer to pull together.

 

Regards,
Chris.

**Comment by cmcornish** [comment]
Hello André,

 

I’m in the UK.

 

I’m sorry that it didn’t work. My apologies for this. I had hoped that it would be straightforward.

 

Would it help if I generated a patch file for you or just describe the changes?

The change was to use CurrentHourSetting in place of CurrentHour on lines 17539, 17542, 17609, 17610, 17927, 17928, 17971 and 17981 to match the chime, alarm, reminder and night light controls (I think I missed the reminder off of my change).

These are all within the timer_callback_s function.

The logic behind this is that these all use 24 hour figures but the CurrentHour is 12/24 hour switchable. 

 

I’ll have a look at the Pico-RGB-Matrix. You are using this for a wall clock? I see it has the remote control too.

 

Regards,

Chris.

**Comment by astlouys** [comment]
Hello Chris,

No problem. I guess this should be very easy for someone with a better knowledge of GitHub. (I must take some time for that in a near future !)

If you tell me that all changes are in timer_callback_s() function, it should be relatively easy for me to add the changes in the baseline code (the line numbers may have changed in my version of the code, but nonetheless, that should be easy). It is true that I use the 24-hour format on my side, so some "glitches" (elegant word for "bugs") may have gone undetected.

I think your development environment has replaced a lot of tab's and / or spaces (GitHub gives zillions of changes), so your comments will direct me to the location of interest in the code ;-)

You could maybe send a copy of the timer_callback_s() by email (my address is in the User Guide) and in the best case, I could be able to simply replace the original one.

As for the Pico-RGB-Matrix, I've been working on my own version of code (derived from Waveshare's) for the last few weeks and yes, in its "normal" mode, it displays day-of-week, date and time. As you mentioned, it has a remote control in the box (very simple, one but...), display is much bigger than Green-Clock. In short, very interesting !

André

**Comment by gatheall** [comment]
Andre, when viewing the commit, you should be able to ignore changes in whitespace; eg, https://github.com/astlouys/Pico-Green-Clock/pull/29/commits/67f1fa275a834d81249167439e796dbac44c27f0?diff=unified&w=1 if using a web browser.  That shows changes are in two functions : 

- a typo in a comment in setup_alarm_variables() 
- various changes in timer_callback_s() to replace 'CurrentHour' with 'CurrentHourSetting' along with changes in comments.

Hope that helps

George

**Comment by astlouys** [comment]
Hello George,

Thank you very much for your help !

With the extracts that you sent, it was easy to fix the code (I even found a second typo in the code with the same "indocator")

Strangely, I see the "Ignore whitespace" in the middle right of the screen when I click on your link, but this option doesn't appear when I display Chris' code. I need to use GitHub more often to get used to all the tricks...

That being said, Chris, my code has changed a lot since the version currently posted on GitHub (line numbering is off by more or less 300 lines in my source code). I know that there must be an easy way to ask Git Hub to integrate your changes, but when I tried, it didn't work :-(
So, I integrated your changes to the code but I'll need to test all the changes that I made in those "300 lines" to make sure the whole thing is relatively stable.

As you know, I'm currently working actively on the Pico-RGB-Matrix and I'm very anxious to post that code on GitHub, hoping that other Pico fans will like it as much as I do !  I will then come back to the Green Clock to make some clean up in the bug fix / features that have been added.

**Comment by cmcornish** [comment]
Thanks for the update André.

 

That explains the problems then. I can see why you are having the trouble. I did try merging the code into the current GitHub version and that went fine. I think the idea is to make a branch of the GitHub code for testing, merge in the pull request to that and then once happy with the code merge the test code into the main branch. Once completed, then you can pull the changes from GitHub onto your local copy. This should then be a simpler merge.

I think people skip the test branch phase and go directly to the merge into main. I haven’t had to do this yet, so it’s just a concept and as you say, unexpected things often happen.

 

I’m not waiting for the changes to be incorporated into your code, so take all the time you need.

 

Regards,
Chris.

**Pull request closed without merging**
